# Worksheet-0 Solution

**Module:** Artificial Intelligence and Machine Learning  
**Institution:** Herald College Kathmandu  
**Submitted Date:** March 9, 2026

---

### Student Details

| Name | ID Number | Group |
| :--- | :--- | :--- |
| **Narayan Lohani** | 2408869 | L6CG15 |

---

<div style="display: flex; justify-content: space-between; align-items: center; border: none;">
  <img src="https://heraldcollege.edu.np/images/footer/footer-logo-dark.svg" width="180" alt="Herald College Logo">
  <img src="
  https://bizzeducation.com/storage/university-partners/May2024/r3iG0n8CHfh1nCAIz5BO.png" width="180" alt="University of Wolverhampton Logo">
</div>


# 4 TO - DO - Task


## 4.1 Exercises on Functions:


### Task - 1:

Create a Python program that converts between different units of measurement.

• The program should:

1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:

1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
   return value.

• Conversion Options:

1. Length:
    - Convert meters (m) to feet (ft).
    - Convert feet (ft) to meters (m).
2. Weight:
    - Convert kilograms (kg) to pounds (lbs).
    - Convert pounds (lbs) to kilograms (kg).
3. Volume:
    - Convert liters (L) to gallons (gal).
    - Convert gallons (gal) to liters (L).


In [ ]:
# Conversion Registry: Map of conversion types
# [Factor, Metric Unit, Imperial Unit]
# The factor converts Metric to Imperial (Metric * Factor = Imperial)

registry = {
    "length": [3.28084, "m", "ft"],
    "weight": [2.20462, "kg", "lbs"],
    "volume": [0.264172, "L", "gal"],
}


def handle_conversion(to_imperial, conversion_type):
    """
    Performs the conversion for length, weight, or volume based on a boolean flag.

    Parameters:
        to_imperial (bool): If True, multiplies by factor. If False, divides.
        conversion_type (str): The category ('length', 'weight', or 'volume').

    Returns:
        float: The converted value, or None if an error occurs.
    """

    factor, metric_unit, imperial_unit = registry[conversion_type]

    from_unit = metric_unit if to_imperial else imperial_unit

    try:
        val = float(input(f"Enter {from_unit} value: "))

        if to_imperial:
            result = val * factor
            print(f"{val} {metric_unit} is {result:.2f} {imperial_unit}")
        else:
            result = val / factor
            print(f"{val} {imperial_unit} is {result:.2f} {metric_unit}")

        return result
    except ValueError:
        print("Error: Please enter a valid numerical value.")
        return None


def units_converter():
    """
    Main controller to prompt user for category and direction.

    Returns:
        float: The result of the conversion, or None for invalid choices.
    """
    print("--- Professional Multi-Unit Converter ---")
    print("1. Length (m/ft)\n2. Weight (kg/lbs)\n3. Volume (L/gal)")
    choice = input("Select category (1-3): ")

    # Map input choice to the string key used in handle_conversion
    type_map = {"1": "length", "2": "weight", "3": "volume"}

    if choice not in type_map:
        print("Invalid category.")
        return None

    # Get the specific units for this category from the registry
    category = type_map[choice]
    _, metric, imperial = registry[category]

    # Dynamically show the units in the direction prompt
    print(f"\nSelect Direction for {category.capitalize()}:")
    print(f"1. Metric ({metric}) to Imperial ({imperial})")
    print(f"2. Imperial ({imperial}) to Metric ({metric})")

    direction = input("Select direction (1 or 2): ")

    if direction not in ["1", "2"]:
        print("Invalid direction.")
        return None

    # Determine boolean: True if Metric -> Imperial (1), False otherwise
    is_imperial = direction == "1"
    # Call the single handler with the determined parameters
    handle_conversion(is_imperial, type_map[choice])


units_converter()


--- Professional Multi-Unit Converter ---
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (L/gal)
Select category (1-3): 2

Select Direction for Weight:
1. Metric (kg) to Imperial (lbs)
2. Imperial (lbs) to Metric (kg)
Select direction (1 or 2): 1
Enter kg value: 50
50.0 kg is 110.23 lbs


### Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:

1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
   of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. **Functions:** Define at least one function for each operation (sum, average, maximum, mini-
   mum).

2. **Error Handling:** Use try-except blocks to handle invalid input (e.g., non-numeric values or
   empty lists).
3. **User Input:** Prompt the user to select the operation and input the list of numbers.
4. **Docstrings:** Include a docstring in each function to describe its purpose, parameters, and
   return value.


In [ ]:
def find_sum(numbers):
    """
    Calculates the total sum of a list of numbers

    Parameters: numbers (list of float)
    Returns: float
    """
    total = 0.0
    for num in numbers:
        total += num
    return total


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters: numbers (list of float)
    Returns: float
    """
    if not numbers:
        return 0.0
    total = find_sum(numbers)
    count = 0
    for _ in numbers:
        count += 1
    return total / count


def find_max(numbers):
    """
    Finds the largest value in the list

    Parameters: numbers (list of float)
    Returns: float
    """
    if not numbers:
        return None
    maximum = numbers[0]
    for num in numbers:
        if num > maximum:
            maximum = num
    return maximum


def find_min(numbers):
    """
    Finds the smallest value in a list

    Parameters: numbers (list of float)
    Returns: float
    """
    if not numbers:
        return None
    minimum = numbers[0]
    for num in numbers:
        if num < minimum:
            minimum = num
    return minimum


def math_operations_tool():
    """
    Main controller for the Math Operations program.
    Prompts user for list of numbers and an operation, then using helper funcitons operates the given list and displays the result.
    """
    print("--- Mathematical Operations on List ---")

    try:
        # Get user input
        raw_input = input("Enter a list of numbers separated by spaces: ")

        numbers = []
        for x in raw_input.split():
            numbers.append(float(x))

        if not numbers:
            print("Error: The list is empty.")
            return

        print("\nChoose an operation:")
        print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")
        choice = input("Enter choice (1-4): ")

        if choice == "1":
            print(f"Result (Sum): {find_sum(numbers)}")
        elif choice == "2":
            print(f"Result (Average): {find_average(numbers)}")
        elif choice == "3":
            print(f"Result (Maximum): {find_max(numbers)}")
        elif choice == "4":
            print(f"Result (Minimum): {find_min(numbers)}")
        else:
            print("Invalid operation choice.")

    except ValueError:
        print("Error: Invalid input. Please enter only numbers separated by spaces.")
    except Exception as e:
        print(f"An error occurred: {e}")


math_operations_tool()


--- Mathematical Operations on List ---
Enter a list of numbers separated by spaces: 5 67 55 10 2342

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1-4): 1
Result (Sum): 2479.0


## 4.2 Exercise on List Manipulation:

### 1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

-   Requirements:

    - Define a function `extract_every_other(lst)` that takes a list `lst` as input and returns a new list containing every other element from the original list.

    - Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Returns a new list containing every other element starting from first index

    Parameters:
        lst (list[int]) : array of numbers
    Returns:
        list[int] : sub-set of numbers
    """
    return lst[::2]


numbers = [1, 2, 3, 4, 5]
print(extract_every_other(numbers))


[1, 3, 5]


### 2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

- Requirements:

    - Define a function `get_sublist(lst, start, end)` that takes a list `lst`, a starting index `start`, and an ending index `end` as input and returns the sublist from `start` to `end` (inclusive).

    - Example: For the input [1, 2, 3, 4, 5, 6] with `start=2` and `end=4`, the output should be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sub list containing element starting from start index to end index

    Parameters:
        lst (list[int]): array of numbers
        start (int): index to start from
        end (int): index to end at
    Returns:
        list[int] : sub-set of numbers
    """
    return lst[start : end + 1]


numbers = [1, 2, 3, 4, 5]
print(get_sublist(numbers, 2, 4))


[3, 4, 5]


### 3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
* Requirements:

    - Define a function `reverse_list(lst)` that takes a list `lst` and returns a reversed list using slicing.
    
    - Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """
    Returns a new list containing element in reversed order

    Parameters:
        lst (list[int]): array of numbers
    Returns:
        list[int] : array of numbers
    """
    return lst[::-1]


numbers = [1, 2, 3, 4, 5]
print(reverse_list(numbers))


[5, 4, 3, 2, 1]


### 4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting sublist.
* Requirements:

    -  Define a function `remove_first_last(lst)` that takes a list `lst` and returns a sublist without the first and last elements using slicing.
    
    - Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """
    Returns a new list removing first and last element of the list

    Parameters:
        lst (list[int]): array of numbers
    Returns:
        list[int] : subset of array of numbers
    """
    return lst[1:-1:]


numbers = [1, 2, 3, 4, 5]
print(remove_first_last(numbers))


[2, 3, 4]


### 5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
* Requirements:

    - Define a function `get_first_n(lst, n)` that takes a list `lst` and an integer n as input and returns the first n elements of the list using slicing.

    - Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """
    Returns a new list with only first n elements

    Parameters:
        lst (list[int]): array of numbers
        n (int): number of elements to extract
    Returns:
        list[int] : subset of array of numbers
    """
    return lst[:n]


numbers = [1, 2, 3, 4, 5]
user_input = int(input("Enter number of elements to extract from first of the list: "))
print(get_first_n(numbers, user_input))


Enter number of elements to extract from first of the list: 3
[1, 2, 3]


### 6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
* Requirements:

    - Define a function `get_last_n(lst, n)` that takes a list `lst` and an integer n as input and returns the last n elements of the list.

    - Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """
    Returns a new list with only last n elements

    Parameters:
        lst (list[int]): array of numbers
        n (int): number of elements to extract
    Returns:
        list[int] : subset of array of numbers
    """
    return lst[-n:]


numbers = [1, 2, 3, 4, 5]
user_input = int(input("Enter number of elements to extract from last of the list : "))
print(get_last_n(numbers, user_input))


Enter number of elements to extract from last of the list : 2
[4, 5]


### 7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.
* Requirements:

    - Define a function `reverse_skip(lst)` that takes a list `lst` and returns a new list containing every second element starting from the second-to-last, moving backward.
    
    - Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    """
    Returns a new list containing elements in reverse order with every second element
    starting from the second-to-last, moving backwards

    Parameters:
        lst (list[int]): array of numbers
    Returns:
        list[int] : subset of array of numbers
    """
    return lst[-2::-2]


numbers = [1, 2, 3, 4, 5, 6]
print(reverse_skip(numbers))


[5, 3, 1]


## 4.3 Exercises on Nested List:

### 1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

* **Requirements**:

    - Define a function `flatten(lst)` that takes a nested list `lst` and returns a flattened version
of the list.

    - Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list

    Parameters:
        lst (list[list]): A nested list

    Returns:
        flat_list (list[int]): A flattened list containing every element of the nested list
    """
    flat_list = []
    # for sub_list in lst:
    #     for ele in sub_list:
    #         flat_list.append(ele)

    for sub_list in lst:
        flat_list.extend(sub_list)

    return flat_list


nested = [[1, 2], [3, 4], [5]]
print(flatten(nested))


[1, 2, 3, 4, 5]


### 2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

* **Requirements**:

    - Define a function `access_nested_element(lst, indices)` that takes a nested list `lst` and
a list of indices `indices`, and returns the element at that position.

    - Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_elements(lst, indices):
    """
    Retuns an element of target postion(indices) from a nested list lst

    Parameters:
        lst (list[list]): A nested list
        indices (list[list]): List of indices

    Returns:
        target (int): Element found in the given indices
    """
    target = lst
    for i in indices:
        target = target[i]
    return target


nested = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

indices = [1, 2]
print(access_nested_elements(nested, indices))


6


### 3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

* **Requirements**:

    -  Define a function `sum_nested(lst)` that takes a nested list `lst` and returns the sum of all
the elements.

    - Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list
    To account for any depth of list, recursive function is used

    Parameters:
        lst (list[list]): Nested list of numbers

    Returns:
        total (int): Sum of all numbers
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


print(sum_nested([[1, 2], [3, [4, 5]], 6]))


21


### 4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

* **Requirements**:

    - Define a function `remove_element(lst, elem)` that removes `elem` from `lst` and returns the
modified list.

    - Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of an element from a nested list

    Parameters:
        lst (list[list]): Nested list
        elem (int): Element to remove

    Returns:
        result (list): Modified nested list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            sub = remove_element(item, elem)
            result.append(sub)
        elif item != elem:
            result.append(item)
    return result


print(remove_element([[1, 2], [3, 2], [4, 5]], 2))


[[1], [3], [4, 5]]


### 5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

* **Requirements**:

    - Define a function `find_max(lst)` that takes a nested list `lst` and returns the maximum
element.
    - Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list

    Parameters:
        lst (list[list]): Nested list

    Returns:
        max_val (int): Maximum value in lst
    """
    max_val = float("-inf")

    for item in lst:
        if isinstance(item, list):
            sub_max = find_max(item)
            if sub_max > max_val:
                max_val = sub_max
        else:
            if item > max_val:
                max_val = item
    return max_val


print(find_max([[1, 2], [3, [4, 5]], 6]))


6


### 6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

* **Requirements**:

    - Define a function `count_occurrences(lst, elem)` that counts the occurrences of `elem` in
the nested list `lst`.

    - Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts occurence of an element in a nested list

    Parameters:
        lst (list[list]): Nested list
        elem (int): Element to count

    Returns:
        count (int): Number of occurrences
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))


3


### 7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
* **Requirements**:

    - Define a function `deep_flatten(lst)` that takes a deeply nested list `lst` and returns a single
flattened list.

    - Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flattens a multi-layered nested list into a single list

    Parameters:
        lst (list[list]): Nested list

    Returns:
        result (list[int]): Flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))


[1, 2, 3, 4, 5, 6, 7, 8]


### 8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

* **Requirements**:

    - Define a function `average_nested(lst)` that takes a nested list `lst` and returns the average
of all the elements.
    
    - Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def recursive_helper(sublist):
    """
    Recursively traverses a nested list to calculate the sum and count of all elements

    Args:
        sublist (list): A list that may contain integers, floats, or other lists

    Returns:
        tuple: A tuple containing (total_sum, element_count).
    """
    total_sum = 0
    element_count = 0
    for item in sublist:
        if isinstance(item, list):
            t, c = recursive_helper(item)
            total_sum += t
            element_count += c
        else:
            total_sum += item
            element_count += 1
    return total_sum, element_count


def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): Nested list containing numerical values.

    Returns:
        float: Average of all elements, or 0 if the list is empty.
    """
    # get total sum and total number of elements from recursive function
    list_sum, ele_count = recursive_helper(lst)
    return list_sum / ele_count if ele_count != 0 else 0


print(average_nested([[1, 2], [3, 4], [5, 6]]))


3.5


# 10 To - Do - NumPy

In [ ]:
import numpy as np
import time


## 10.1 Basic Vector and Matrix Operation with Numpy.

### Problem - 1: Array Creation:
Complete the following Tasks:

  1. Initialize an empty array with size 2X2.



In [ ]:
empty_arr = np.empty((2, 2))
print("Empty Array of (2,2) : \n", empty_arr)


Empty Array of (2,2) : 
 [[6.52289340e-310 2.74130766e-315]
 [1.24256733e-219 3.77291555e-310]]


  2. Initialize an all one array with size 4X2.
  


In [ ]:
one_arr = np.ones((4, 2))
print("Ones Array of (4,2) : \n", one_arr)


Ones Array of (4,2) : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
filled_shape = (2, 4)
filled_scalar = 7
filled_type = float
filled_arr = np.full(filled_shape, filled_scalar, filled_type)
print(
    f"Array of shape - {filled_shape} filled with - {filled_scalar} of type - {filled_type} : \n",
    filled_arr,
)


Array of shape - (2, 4) filled with - 7 of type - <class 'float'> : 
 [[7. 7. 7. 7.]
 [7. 7. 7. 7.]]


 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
  

In [ ]:
sample_arr_for_zeros_like = [
    [1, 3, 5],
    [4, 2, 6],
]

zeros_like_arr = np.zeros_like(sample_arr_for_zeros_like, dtype=float)

print("--- Initial Array ---")
print(np.array(sample_arr_for_zeros_like))

print("\n--- After zeros_like (dtype=float) ---")
print(zeros_like_arr)


--- Initial Array ---
[[1 3 5]
 [4 2 6]]

--- After zeros_like (dtype=float) ---
[[0. 0. 0.]
 [0. 0. 0.]]



  5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
  

In [ ]:
sample_arr_for_ones_like = [
    [1, 3, 5],
    [4, 2, 6],
]

ones_like_arr = np.ones_like(sample_arr_for_ones_like, dtype=int)

print("--- Initial Array ---")
print(np.array(sample_arr_for_ones_like))

print("\n--- After ones_like (dtype=int) ---")
print(ones_like_arr)


--- Initial Array ---
[[1 3 5]
 [4 2 6]]

--- After ones_like (dtype=int) ---
[[1 1 1]
 [1 1 1]]



  6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
  

In [ ]:
new_list = [1, 2, 3, 4]
print(f"List : {new_list}\nType: {type(new_list)}", end="\n\n")

new_list_arr = np.array(new_list)
print(f"Numpy Array : {new_list_arr}\nType: {type(new_list_arr)}", end="\n")


List : [1, 2, 3, 4]
Type: <class 'list'>

Numpy Array : [1 2 3 4]
Type: <class 'numpy.ndarray'>


---

### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
arr_10_to_49 = np.arange(10, 50)
print("Array with values ranging from 10 to 49 : \n", arr_10_to_49)


Array with values ranging from 10 to 49 : 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}


In [ ]:
arr_0_to_8 = np.arange(9)
arr_0_to_8_3_by_3 = arr_0_to_8.reshape((3, 3))
print("Array ranging from 0 to 8 in 3x3 form : \n", arr_0_to_8_3_by_3)


Array ranging from 0 to 8 in 3x3 form : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
arr_identity_3_3 = np.eye(3)
print("Identity matrix of 3x3 :\n", arr_identity_3_3)


Identity matrix of 3x3 :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}


In [ ]:
random_arr_30 = np.random.random(30)
avg_random_arr_30 = random_arr_30.mean()
print("Mean of random array of size 30 : ", avg_random_arr_30)


Mean of random array of size 30 :  0.5762957029683636


5. Create a 10X10 array with random values and find the minimum and maximum values.


In [ ]:
random_arr_10_10 = np.random.random((10, 10))
max_random_arr_10_10 = random_arr_10_10.max()
min_random_arr_10_10 = random_arr_10_10.min()

print("In a random matrix of 10x10 :")
print(f"Maximum Value : {max_random_arr_10_10}\nMinimum Value : {min_random_arr_10_10}")


In a random matrix of 10x10 :
Maximum Value : 0.9929031809417508
Minimum Value : 0.012839839798187036


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
arr_zeros_10 = np.zeros(10)
arr_zeros_10[4] = 1
print("Zero Array of size 10 with 1 in fifth element : \n", arr_zeros_10)


Zero Array of size 10 with 1 in fifth element : 
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
given_list = [1, 2, 0, 0, 4, 0]
given_arr = np.array(given_list)
reversed_given_arr = given_arr[::-1]
print(f"Given array : {given_arr}\n")
print(f"Reversed array : {reversed_given_arr}\n")


Given array : [1 2 0 0 4 0]

Reversed array : [0 4 0 0 2 1]



8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
size = 5
pad_size = 3
array_border = np.ones((size, size))
array_border[1:-1, 1:-1] = 0
# Pad it with a thickness of 1, using the constant value 1
padder_arr = np.pad(
    np.zeros((pad_size, pad_size)), pad_width=1, mode="constant", constant_values=1
)
print(f"2D array of size - {size} with 1 on border and 0 inside :\n", padder_arr)


2D array of size - 5 with 1 on border and 0 inside :
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
arr_checkerboard = np.zeros((8, 8))
arr_checkerboard[::2, ::2] = 1
arr_checkerboard[1::2, 1::2] = 1
print(arr_checkerboard)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### Problem - 3: Array Operations:

For the following arrays:

`x = np.array([[1,2],[3,5]])` and `y = np.array([[5,6],[7,8]])`

`v = np.array([9,10])` and `w = np.array([11,12])`

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
print(f"X :\n{x}\n\nY :\n{y}\n\nV :\n{v}\n\nW :\n{w}")


X :
[[1 2]
 [3 5]]

Y :
[[5 6]
 [7 8]]

V :
[ 9 10]

W :
[11 12]


Complete all the task using numpy:

1. Add the two array.

In [ ]:
print("Sum of X and Y:\n", x + y)
print("\nSum of v and w:\n", w + v)


Sum of X and Y:
 [[ 6  8]
 [10 13]]

Sum of v and w:
 [20 22]


2. Subtract the two array.

In [ ]:
print("Differenece of X and Y:\n", x - y)
print("\nDifferenece of v and w:\n", w - v)


Differenece of X and Y:
 [[-4 -4]
 [-4 -3]]

Differenece of v and w:
 [2 2]


3. Multiply the array with any integers of your choice.


In [ ]:
print(f"3 * x : \n", 3 * x, end="\n\n")
print(f"2 * y : \n", 2 * y, end="\n\n")
print(f"5 * w : \n", 5 * w, end="\n\n")
print(f"10 * v : \n", 10 * v, end="\n\n")


3 * x : 
 [[ 3  6]
 [ 9 15]]

2 * y : 
 [[10 12]
 [14 16]]

5 * w : 
 [55 60]

10 * v : 
 [ 90 100]



4. Find the square of each element of the array.

In [ ]:
print(f"Square of each element in x:\n", x**2, end="\n\n")
print(f"Square of each element in y:\n", np.square(y), end="\n\n")
print(f"Square of each element in v:\n", v**2, end="\n\n")
print(f"Square of each element in w:\n", np.square(w), end="\n\n")


Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Square of each element in y:
 [[25 36]
 [49 64]]

Square of each element in v:
 [ 81 100]

Square of each element in w:
 [121 144]



5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
dot_v_w = np.dot(v, w)
dot_x_y = np.dot(x, y)

print("Dot product between v and w : \n", dot_v_w)
print("Dot product between x and y : \n", dot_x_y)


Dot product between v and w : 
 219
Dot product between x and y : 
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
print(f"Shape of v : {v.shape} and Shape of w : {w.shape}")
vstack_v_w = np.vstack((v, w))
print(f"Vertically Stacking v and w : \n", vstack_v_w)

print(f"Shape of x: {x.shape} and Shape of y : {y.shape}")
concat_x_y = np.concatenate((x, y), axis=0)
print(f"Concatenating x and y along row :\n", concat_x_y)


Shape of v : (2,) and Shape of w : (2,)
Vertically Stacking v and w : 
 [[ 9 10]
 [11 12]]
Shape of x: (2, 2) and Shape of y : (2, 2)
Concatenating x and y along row :
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
print(f"Shape of x: {x.shape} and Shape of v : {v.shape}")
try:
    concat_x_v = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("Error: ", e)


Shape of x: (2, 2) and Shape of v : (2,)
Error:  all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


When we try to run the concatenate x and v, we observe a ValueError because of a Dimension Mismatch.
* x is a 2D array: Its shape is `(2, 2)`, meaning it has 2 rows and 2 columns.
* v is a 1D array: Its shape is `(2,)`, which is just a flat list of 2 elements.

In NumPy, np.concatenate requires all input arrays to have the exact same number of dimensions.
Because it doesn't know if that 1D line should be treated as a new row or a new column, we get the above error.

### Problem - 4: Matrix Operations:

For the following arrays:

`A = np.array([[3,4],[7,8]])`

`B = np.array([[5,3],[2,1]]);`


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("A : \n", A)
print("B : \n", B)


A : 
 [[3 4]
 [7 8]]
B : 
 [[5 3]
 [2 1]]


#### Prove following with Numpy:

  1. Prove A.A<sup>−1</sup> = I.


In [ ]:
A_inv = np.linalg.inv(A)
print("Inverse of matrix A : \n", A_inv, end="\n\n")

dot_A_Ainv = np.dot(A, A_inv)
print("Dot product of A and A inverse : \n", dot_A_Ainv, end="\n\n")

check = np.allclose(dot_A_Ainv, np.eye(A.shape[0]))
print(f"Is it effectively the Identity Matrix? {check}")


Inverse of matrix A : 
 [[-2.    1.  ]
 [ 1.75 -0.75]]

Dot product of A and A inverse : 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is it effectively the Identity Matrix? True



  2. Prove AB &ne; BA.


In [ ]:
dot_A_B = np.dot(A, B)
dot_B_A = np.dot(B, A)

print("Dot product of A and B (A.B) : \n", dot_A_B, end="\n\n")
print("Dot product of B and A (B.A) : \n", dot_B_A, end="\n\n")

print(
    f"Is each element of A.B close to B.A? \n{np.isclose(dot_A_B, dot_B_A)}", end="\n\n"
)

is_commutative = np.allclose(dot_A_B, dot_B_A)
print(f"Is A.B equal to B.A? {is_commutative}")


Dot product of A and B (A.B) : 
 [[23 13]
 [51 29]]

Dot product of B and A (B.A) : 
 [[36 44]
 [13 16]]

Is each element of A.B close to B.A? 
[[False False]
 [False False]]

Is A.B equal to B.A? False



  3. Prove (AB)<sup>T</sup> = B<sup>T</sup>A<sup>T</sup>.

In [ ]:
dot_A_B_trans = np.transpose(dot_A_B)
B_trans = np.transpose(B)
A_trans = np.transpose(A)
dot_Btrans_Atrans = np.dot(B_trans, A_trans)

print("Transpose of dot product of A and B (A.B)T : \n", dot_A_B_trans, end="\n\n")
print(
    "Dot product of B transpose and A transpose (B)T.(A)T : \n",
    dot_Btrans_Atrans,
    end="\n\n",
)

comparison = np.isclose(dot_A_B_trans, dot_Btrans_Atrans)
print(f"Is (A.B)T equal to BT.AT? \n{comparison}")

print(f"\nVerification: {np.all(comparison)}")


Transpose of dot product of A and B (A.B)T : 
 [[23 51]
 [13 29]]

Dot product of B transpose and A transpose (B)T.(A)T : 
 [[23 51]
 [13 29]]

Is (A.B)T equal to BT.AT? 
[[ True  True]
 [ True  True]]

Verification: True


#### Solve the following system of Linear equation using inverse Method

$$2x − 3y + z = −1$$

$$x − y + 2z = −3$$

$$3x + y − z = 9$$


{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
# Matrix representation of A and B
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [ ]:
# Inverse of A
A_inv = np.linalg.inv(A)
print("Inverse of Matrix A:")
print(A_inv, end="\n\n")

# Solving for X (X = A_inv . B)
solution_inverse_method = np.dot(A_inv, B)

print("Results calcualated using inverse method (x, y, z):")
print(solution_inverse_method)

print("Results calculated using np.linalg.solve (x,y,z) : ")
print(np.linalg.solve(A, B))


Inverse of Matrix A:
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Results calcualated using inverse method (x, y, z):
[ 2.  1. -2.]
Results calculated using np.linalg.solve (x,y,z) : 
[ 2.  1. -2.]


## 10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

In [ ]:
def time_the_operation(func, *args):
    """
    Measures the time taken by a function to execute.

    Params:
        func (callable): The function to time.
        *args: Arguments to pass to the function.

    Returns:
        float: Time taken in seconds for the function to execute.
    """
    start_time = time.time()
    func(*args)
    end_time = time.time()
    return end_time - start_time


# Initialize data
SIZE = 1_000_000
list_a = list(range(SIZE))
list_b = list(range(SIZE))
arr_a = np.arange(SIZE)
arr_b = np.arange(SIZE)


### 1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
def list_addition(l1, l2):
    """
    Performs element-wise addition of two lists.

    Params:
        l1 (list): First list of numbers.
        l2 (list): Second list of numbers.
    """
    for x, y in zip(l1, l2):
        x + y


def numpy_addition(a1, a2):
    """
    Performs element-wise addition of two numpy arrays.

    Params:
        a1 (np.ndarray): First array.
        a2 (np.ndarray): Second array.
    """
    a1 + a2


t_add_list = time_the_operation(list_addition, list_a, list_b)
t_add_np = time_the_operation(numpy_addition, arr_a, arr_b)

print(f"--- Element-wise Addition (Size: {SIZE:,}) ---")
print(f"Python List Time: {t_add_list:.6f} seconds")
print(f"NumPy Array Time: {t_add_np:.6f} seconds")
print(f"Speedup: {t_add_list / t_add_np:.2f}x")


--- Element-wise Addition (Size: 1,000,000) ---
Python List Time: 0.056493 seconds
NumPy Array Time: 0.004656 seconds
Speedup: 12.13x


### 2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [ ]:
def list_multiplication(l1, l2):
    """
    Performs element-wise multiplication of two lists.

    Params:
        l1 (list): First list of numbers.
        l2 (list): Second list of numbers.

    Returns:
        list: List containing element-wise products.
    """
    for x, y in zip(l1, l2):
        x * y


def numpy_multiplication(a1, a2):
    """
    Performs element-wise multiplication of two numpy arrays.

    Params:
        a1 (np.ndarray): First array.
        a2 (np.ndarray): Second array.
    """
    a1 * a2


t_mul_list = time_the_operation(list_multiplication, list_a, list_b)
t_mul_np = time_the_operation(numpy_multiplication, arr_a, arr_b)

print(f"--- Element-wise Multiplication (Size: {SIZE:,}) ---")
print(f"Python List Time: {t_mul_list:.6f} seconds")
print(f"NumPy Array Time: {t_mul_np:.6f} seconds")
print(f"Speedup: {t_mul_list / t_mul_np:.2f}x")


--- Element-wise Multiplication (Size: 1,000,000) ---
Python List Time: 0.106919 seconds
NumPy Array Time: 0.004742 seconds
Speedup: 22.55x


### 3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
def list_dot_product(l1, l2):
    """
    Computes the dot product of two lists.

    Params:
        l1 (list): First list of numbers.
        l2 (list): Second list of numbers.
    """
    dot = 0
    for x, y in zip(l1, l2):
        dot += x * y


def numpy_dot_product(a1, a2):
    """
    Computes the dot product of two numpy arrays.

    Params:
        a1 (np.ndarray): First array.
        a2 (np.ndarray): Second array.
    """
    np.dot(a1, a2)


t_dot_list = time_the_operation(list_dot_product, list_a, list_b)
t_dot_np = time_the_operation(numpy_dot_product, arr_a, arr_b)

print(f"--- Dot Product (Size: {SIZE:,}) ---")
print(f"Python List Time: {t_dot_list:.6f} seconds")
print(f"NumPy Array Time: {t_dot_np:.6f} seconds")
print(f"Speedup: {t_dot_list / t_dot_np:.2f}x")


--- Dot Product (Size: 1,000,000) ---
Python List Time: 0.171764 seconds
NumPy Array Time: 0.002188 seconds
Speedup: 78.49x


### 4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
MAT_SIZE = 1000
mat_list_a = [[float(i) for i in range(MAT_SIZE)] for _ in range(MAT_SIZE)]
mat_list_b = [[float(i) for i in range(MAT_SIZE)] for _ in range(MAT_SIZE)]
mat_np_a = np.array(mat_list_a)
mat_np_b = np.array(mat_list_b)


def list_matrix_mul(A, B):
    """
    Performs matrix multiplication using Python lists.

    Params:
        A (list[list[float]]): First matrix as a list of lists.
        B (list[list[float]]): Second matrix as a list of lists.
    """
    # Initialize result matrix with zeros
    result = [[0.0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]


def numpy_matrix_mul(A, B):
    """
    Performs matrix multiplication using numpy arrays.

    Params:
        A (np.ndarray): First matrix.
        B (np.ndarray): Second matrix.
    """
    np.matmul(A, B)


print(f"--- Matrix Multiplication ({MAT_SIZE}x{MAT_SIZE}) ---")
# NumPy Timing
t_mat_np = time_the_operation(numpy_matrix_mul, mat_np_a, mat_np_b)
print(f"NumPy Array Time: {t_mat_np:.6f} seconds")

# List Timing (Slow!)
print("Calculating List Matrix Mul")
t_mat_list = time_the_operation(list_matrix_mul, mat_list_a, mat_list_b)
print(f"Python List Time: {t_mat_list:.6f} seconds")

print(f"Speedup: {t_mat_list / t_mat_np:.2f}x")


--- Matrix Multiplication (1000x1000) ---
NumPy Array Time: 0.125222 seconds
Calculating List Matrix Mul
Python List Time: 207.184115 seconds
Speedup: 1654.53x
