In [ ]:
import numpy as np
import time


In [ ]:
import sys

if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("hello world")
    print(f"Python version: {sys.version}")
else:
    print("Pleas use Python 3.6 or higer")


hello world
Python version: 3.14.3 (main, Feb  3 2026, 15:32:20) [Clang 17.0.0 (clang-1700.6.3.2)]


In [ ]:
my_list = [4, 6, 3]
print("Original List: ", my_list)

my_list.append(4)
print("Modified List: ", my_list)

my_tuple = (1, 3, 4)
print("Original Tuple: ", my_tuple)
# my_tuple.append(5)


Original List:  [4, 6, 3]
Modified List:  [4, 6, 3, 4]
Original Tuple:  (1, 3, 4)


In [ ]:
age = 23  # int
pi = 3.14  # float
temperature = -5.5  # float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))


data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


In [ ]:
name = "Alice"
greeting = "Hello"
address = "123 Main St"
print("data type of the variable name = ", type(name))
print("data type of the variable greeting = ", type(greeting))
print("data type of the variable address = ", type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])


data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


In [ ]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
print(mixed_list)


[False, 'Hello', True]


In [ ]:
colors = ("red", "green", "yellow", "blue")
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
# colors[0] = 'purple'
# will generate an error as tuple is immutable.


First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


In [ ]:
# initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2, 3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")


 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [ ]:
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")


Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim)  # Output: 1
# For a 2-D array:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.ndim)  # Output: 2
# For a 3-D array:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_3d.ndim)  # Output: 3


1
2
3


In [ ]:
print(arr_1d.shape)  # Output: (5,)
print(arr_2d.shape)  # Output: (2, 3)
print(arr_3d.shape)  # Output: (2, 2, 3)


(5,)
(2, 3)
(2, 2, 3)


In [ ]:
print(arr_1d.size)  # Output: 5
print(arr_2d.size)  # Output: 6
print(arr_3d.size)  # Output: 12


5
6
12


In [ ]:
print(arr_1d.dtype)  # Output: int64 (or int32)
arr_float = np.array([1.1, 2.2, 3.3])
print(arr_float.dtype)  # Output: float64


int64
float64


In [ ]:
# .itemsize Size of Each Element in Bytes: Returns the size (in bytes) of one array element.
print(arr_1d.itemsize)  # Output: 8 (for int64)


8


In [ ]:
# .nbytes Total Memory Consumption: Returns the total memory (in bytes) used by the array.
print(arr_1d.nbytes)  # Output: 40 (5 elements \times 8 bytes each for int64)


40


In [ ]:
print(arr_2d.T)
# Output:
# [[1 4]
# [2 5]
# [3 6]]


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# .flat Flattening the Array: Returns an iterator over a 1D representation of the array.
for item in arr_2d.flat:
    print(item, end=" ")  # Output: 1 2 3 4 5 6


1 2 3 4 5 6 

In [ ]:
# .real and .imag - Real and Imaginary Parts: Used for complex number arrays.
arr_complex = np.array([1 + 2j, 3 + 4j])
print(arr_complex.real)  # Output: [1. 3.]
print(arr_complex.imag)  # Output: [2. 4.]


[1. 3.]
[2. 4.]


In [ ]:
# .astype(dtype) Convert Data Type: Converts the array elements to a specified data type.
arr_float = arr_2d.astype(float)
print(arr_float)
# Output:
# [[1. 2. 3.]
# [4. 5. 6.]]


[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# Create an array with shape (2, 3)
array = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape to (3, 2), keeping 6 elements
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)
# Expected Outputs:
# Original Shape: (2, 3)
# Reshaped Shape: (3, 2)
print(array)
print(reshaped_array)


Original Shape: (2, 3) 
Reshaped Shape: (3, 2)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x)  # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(3, 10.9, 0.5)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)


[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5
 10.  10.5]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
# 50 values between 1 and 10:
print(np.linspace(1, 10))  # third parameter default num=50
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [ ]:
# Create arrays of specified shapes
ones_array = np.ones((2, 3))  # Shape: (2, 3)
zeros_array = np.zeros((3, 2))  # Shape: (3, 2)
empty_array = np.empty((2, 2))  # Shape: (2, 2)
identity_matrix = np.eye(3)  # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep="\n\n")


[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

array_from_list = np.array([1, 2, 3])  # [1 2 3]
array_from_tuple = np.array((4, 5, 6))  # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]])  # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep="\n\n")


[1 2 3]

[4 5 6]

[[1 2 3]
 [4 5 6]]


In [ ]:
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = (
    np.zeros(arr.shape),
    np.ones(arr.shape),
    np.empty(arr.shape),
)  # Shape: (2,3)
print(arr, zeros, ones, empty, sep="\n\n")


[[1 2 3]
 [4 5 6]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]])  # Shape: (2, 2)
print(arr1, arr2, sep="\n\n")
# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked, vstacked, colstacked, sep="\n\n")


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 5]
 [2 6]]


In [ ]:
# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]])  # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]])  # Shape: (2, 2, 1)
# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (third dimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)


Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


In [ ]:
# Incorrect shapes
arr1 = np.array([[1, 2], [3, 4]])  # shape (2, 2)
arr2 = np.array([5, 6])  # shape (2,)
# Attempting horizontal stack
try:
    hstacked = np.hstack((arr1, arr2))  # Error due to dimension mismatch
except ValueError as e:
    print(f"Error: {e}")
# Solution: Reshape arr2 to match arr1’s dimensions
arr2 = np.array([5, 6]).reshape(2, 1)  # shape (2, 1)
hstacked = np.hstack((arr1, arr2))  # No error
print(hstacked)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[1 2 5]
 [3 4 6]]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]])  # shape (2, 2)
# Attempting horizontal stack (this will fail)
try:
    hstacked = np.hstack((arr1, arr2))  # Error due to shape mismatch
except ValueError as e:
    print(f"Error: {e}")
# Solution: Make sure the number of rows in both arrays is the same before stacking
arr2 = np.array([[7, 8, 9], [10, 11, 12]])  # shape (2, 3)
hstacked = np.hstack((arr1, arr2))  # Works fine
print(hstacked)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]], dtype=int)
arr2 = np.array([5, 6], dtype=float)
# Attempting horizontal stack (this will work, but can lead to unexpected results)
try:
    hstacked = np.vstack((arr1, arr2))
except ValueError as e:
    print(f"Error: {e}")
# Solution: Convert the data types to match each other explicitly, if needed:
arr2 = np.array([5, 6], dtype=int)  # Match the type of arr1
vstacked = np.vstack((arr1, arr2))  # Works fine
print(hstacked)


[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
arr1 = np.array([[[1, 2], [3, 4]]])  # shape (1, 2, 2)
arr2 = np.array([[5, 6], [7, 8]])  # shape (2, 2)
# Attempting stacking with 3D and 2D arrays
try:
    vstacked = np.vstack((arr1, arr2))  # Error due to too many dimensions
except ValueError as e:
    print(f"Error: {e}")
# Solution: Reshape arr1 to be 2D (or flatten it) before stacking
arr1 = arr1.reshape(2, 2)  # Now it’s shape (2, 2)
vstacked = np.vstack((arr1, arr2))  # Works fine
print(vstacked)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr = np.arange(10)
arr_greater_5 = arr[arr > 5]
print(arr_greater_5)


[6 7 8 9]


In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing elements using indexing
print(array[0, 1])  # Output: 2 (first row, second column)
print(array[-1, -1])  # Output: 9 (last row, last column)
# Slicing the array
print(array[0:2, 1:3])  # Output: [[2, 3], [5, 6]]


2
9
[[2 3]
 [5 6]]


In [ ]:
# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
# Attempting to access an element out of bounds
try:
    print(array[2, 1])
except IndexError as e:
    print(f"Error: {e}")


Error: index 2 is out of bounds for axis 0 with size 2


In [ ]:
# Example of basic ufuncs: square and square root
arr = np.array([1, 4, 9, 16])
# Square every element
squared = np.square(arr)
# Square root of every element
sqrt = np.sqrt(arr)
print(f"Squared: {squared}")
print(f"Square root: {sqrt}")


Squared: [  1  16  81 256]
Square root: [1. 2. 3. 4.]


In [ ]:
# Trigonometric ufuncs
angles = np.array([0, np.pi / 4, np.pi / 2])
sine_values = np.sin(angles)
# Logarithmic ufuncs
log_values = np.log(arr)
print(f"Sine values: {sine_values}")
print(f"Logarithmic values: {log_values}")


Sine values: [0.         0.70710678 1.        ]
Logarithmic values: [0.         1.38629436 2.19722458 2.77258872]


In [ ]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
# Compute determinant
det = np.linalg.det(A)
# Compute inverse
inverse = np.linalg.inv(A)
# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(f"Matrix Product:\n{product}", end="\n\n")
print(f"Determinant: {det}", end="\n\n")
print(f"Inverse:\n{inverse}", end="\n\n")
print(f"Eigenvalues: {eigvals},\n\nEigenvectors:\n{eigvecs}", end="\n\n")


Matrix Product:
[[19 22]
 [43 50]]

Determinant: -2.0000000000000004

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues: [-0.37228132  5.37228132],

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]



In [ ]:
A = np.array([[1], [2], [3]])  # Shape (3,1) 3 rows, 1 column
B = np.array([10, 20, 30])  # Shape (3,) 1D array (3 elements)
C = A + B  # Works! Result shape: (3,3)
print(C)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
A = np.array([[1, 2, 3]])  # Shape (1,3)
B = np.array([[4], [5], [6]])  # Shape (3,1)
C = A + B  # Works! Result shape: (3,3)
print(C)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)
# Using a loop
start_time = time.time()
result_loop = np.zeros(size)
for i in range(size):
    result_loop[i] = a[i] + b[i]
end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")
# Using NumPy’s vectorized operations
start_time = time.time()
result_vectorized = a + b  # Element-wise addition
end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")
# Performance improvement factor
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")


Loop Execution Time: 0.95095 seconds
Vectorized Execution Time: 0.00251 seconds
Vectorization is approximately 378.57 times faster!
